modLoader="javafml"
loaderVersion="[47,)"
license="GNU Affero General Public License v3.0"
issueTrackerURL="https://github.com/RainbowVille/minegasm/issues"
[[mods]]
modId="minegasm"
version="0.4.0"
displayName="Minegasm"
#updateJSONURL="https://www.minegasm.net/updates.json"
displayURL="https://www.minegasm.net/"
logoFile="minegasm.png"
authors="RSwoop"
description='''
  Just a simple mod to bring some gasm into Minecraft. ;)
'''
[[dependencies.minegasm]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.minegasm]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
