title: Minegasm
logo: /minegasm.png
repository: RainbowVille/minegasm
description: A haptics Minecraft (Neo)Forge mod
theme: just-the-docs
color_scheme: minegasm
callouts:
  warning:
    color: red
  highlight:
    color: blue
plugins:
  - jemoji
