# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build with Gradle (FG_2.1)

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      java-version:
        required: true
        type: string

jobs:
  gradle:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: forge/fg-2.1
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK ${{ inputs.java-version }}
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: ${{ inputs.java-version }}
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: 4.10.3
    - name: Run Gradle build
      working-directory: forge/fg-2.1
      run: gradle :${{ inputs.version }}:build
    - uses: actions/upload-artifact@v4
      with:
        name: Minegasm-${{ inputs.version }}
        path: forge/fg-2.1/${{ inputs.version }}/build/libs/*
