name: Build 1.17

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'forge/fg-6.0/1.17/**'
      - '.github/workflows/fg-6.0.yml'
      - '.github/workflows/gradle-forge-1.17.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'forge/fg-6.0/1.17/**'
      - '.github/workflows/fg-6.0.yml'
      - '.github/workflows/gradle-forge-1.17.yml'

jobs:
  build:
    uses: ./.github/workflows/fg-6.0.yml
    with:
      version: 1.17
      java-version: 16