name: Build 1.16

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'forge/1.16/**'
      - '.github/workflows/gradle-forge.yml'
      - '.github/workflows/gradle-forge-1.16.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'forge/1.16/**'
      - '.github/workflows/gradle-forge.yml'
      - '.github/workflows/gradle-forge-1.16.yml'

jobs:
  build:
    uses: ./.github/workflows/gradle-forge.yml
    with:
      version: 1.16
      java-version: 11