name: Build 1.18

on:
  push:
    branches: [ main ]
    paths:
      - '1.18/**'
      - '.github/workflows/gradle-1.18.yml'
  pull_request:
    branches: [ main ]
    paths:
      - '1.18/**'
      - '.github/workflows/gradle-1.18.yml'

jobs:
  gradle:
    uses: ./.github/workflows/gradle.yml
    with:
      version: 1.18
      java-version: 17