# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build 1.18+

on:
  push:
    branches: [ main ]
    paths:
      - '1.18/**'
      - '.github/workflows/gradle-1.18.yml'
  pull_request:
    branches: [ main ]
    paths:
      - '1.18/**'
      - '.github/workflows/gradle-1.18.yml'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - mcVer: 1.18.2
            mcRange: "[1.19,1.19)"
            forgeVer: 40.2.0
            forgeRange: "[40,)"
          - mcVer: 1.19.4
            mcRange: "[1.19,1.20)"
            forgeVer: 45.1.0
            forgeRange: "[45,)"
          - mcVer: 1.20.1
            mcRange: "[1.20,1.21)"
            forgeVer: 47.0.19
            forgeRange: "[47,)"

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Grant execute permission for gradlew
      run: chmod +x 1.18/gradlew
    - name: Edit Toml
      run: sed -i.bak -e s/\\[40,\\)/${{ matrix.forgeRange }}/ -e s/\\[1.18,1.19\\)/${{ matrix.mcRange }}/ 1.18/src/main/resources/META-INF/mods.toml
    - name: Gradle Build Action
      uses: gradle/gradle-build-action@v2
      with:
        build-root-directory: 1.18
        arguments: |
          build
          -PmcVer=${{ matrix.mcVer }}
          -PforgeVer=${{ matrix.forgeVer }}
    - uses: actions/upload-artifact@v2
      with:
        name: Package
        path: 1.18/build/libs/*-${{ matrix.mvVer }}-*
