name: Build 1.19

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'forge/fg-6.0/1.19/**'
      - '.github/workflows/fg-6.0.yml'
      - '.github/workflows/gradle-forge-1.19.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'forge/fg-6.0/1.19/**'
      - '.github/workflows/fg-6.0.yml'
      - '.github/workflows/gradle-forge-1.19.yml'

jobs:
  build:
    uses: ./.github/workflows/fg-6.0.yml
    with:
      version: 1.19
      java-version: 17