name: Build 1.14.4

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'forge/fg-6.0/1.14.4/**'
      - '.github/workflows/fg-6.0.yml'
      - '.github/workflows/gradle-forge-1.14.4.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'forge/fg-6.0/1.14.4/**'
      - '.github/workflows/fg-6.0.yml'
      - '.github/workflows/gradle-forge-1.14.4.yml'

jobs:
  build:
    uses: ./.github/workflows/fg-6.0.yml
    with:
      version: 1.14.4
      java-version: 8