# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build 1.20

on:
  push:
    branches: [ main ]
    paths:
      - '1.20/**'
      - '.github/workflows/gradle-1.20.yml'
  pull_request:
    branches: [ main ]
    paths:
      - '1.20/**'
      - '.github/workflows/gradle-1.20.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 17
    - name: Grant execute permission for gradlew
      run: chmod +x 1.20/gradlew
    - name: Gradle Build Action
      uses: gradle/gradle-build-action@v2
      with:
        arguments: :1.20:build
    - uses: actions/upload-artifact@v3
      with:
        name: Package
        path: 1.20/build/libs/*-1.20*
