name: Build 1.16

on:
  push:
    branches: [ main ]
    paths:
      - '1.16/**'
      - '.github/workflows/gradle.yml'
      - '.github/workflows/gradle-1.16.yml'
  pull_request:
    branches: [ main ]
    paths:
      - '1.16/**'
      - '.github/workflows/gradle.yml'
      - '.github/workflows/gradle-1.16.yml'

jobs:
  gradle:
    uses: ./.github/workflows/gradle.yml
    with:
      version: 1.16
      java-version: 11