name: Build 1.17

on:
  push:
    branches: [ main ]
    paths:
      - '1.17/**'
      - '.github/workflows/gradle-1.17.yml'
  pull_request:
    branches: [ main ]
    paths:
      - '1.17/**'
      - '.github/workflows/gradle-1.17.yml'

jobs:
  gradle:
    uses: ./.github/workflows/gradle.yml
    with:
      version: 1.17
      java-version: 16