name: Build 1.19

on:
  push:
    branches: [ main ]
    paths:
      - '1.19/**'
      - '.github/workflows/gradle-1.19.yml'
  pull_request:
    branches: [ main ]
    paths:
      - '1.19/**'
      - '.github/workflows/gradle-1.19.yml'

jobs:
  gradle:
    uses: ./.github/workflows/gradle.yml
    with:
      version: 1.19
      java-version: 17