# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build with Gradle

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      java-version:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./forge
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ inputs.java-version }}
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: ${{ inputs.java-version }}
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Gradle Build Action
      uses: gradle/gradle-build-action@v2.4.2
      gradle-executable: ./forge
      with:
        arguments: :${{ inputs.version }}:build
    - uses: actions/upload-artifact@v3
      with:
        name: Minegasm-${{ inputs.version }}
        path: ${{ inputs.version }}/build/libs/*-${{ inputs.version }}*
