name: Build 1.16.5

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'forge/fg-6.0/1.16.5/**'
      - '.github/workflows/fg-6.0.yml'
      - '.github/workflows/gradle-forge-1.16.5.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'forge/fg-6.0/1.16.5/**'
      - '.github/workflows/fg-6.0.yml'
      - '.github/workflows/gradle-forge-1.16.5.yml'

jobs:
  build:
    uses: ./.github/workflows/fg-6.0.yml
    with:
      version: 1.16.5
      java-version: 8