name: Build 1.20

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'forge/fg-6.0/1.20/**'
      - '.github/workflows/fg-6.0.yml'
      - '.github/workflows/gradle-forge-1.20.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'forge/fg-6.0/1.20/**'
      - '.github/workflows/fg-6.0.yml'
      - '.github/workflows/gradle-forge-1.20.yml'

jobs:
  build:
    uses: ./.github/workflows/fg-6.0.yml
    with:
      version: 1.20
      java-version: 17