# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build 1.12

on:
  push:
    branches: [ main ]
    paths:
      - '1.12/**'
      - '.github/workflows/gradle-1.12.yml'
  pull_request:
    branches: [ main ]
    paths:
      - '1.12/**'
      - '.github/workflows/gradle-1.12.yml'

jobs:
  build:
    uses: ./.github/workflows/gradle.yml
    with:
      version: 1.12
      java-version: 11