name: Build 1.18

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'forge/fg-6.0/1.18/**'
      - '.github/workflows/fg-6.0.yml'
      - '.github/workflows/gradle-forge-1.18.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'forge/fg-6.0/1.18/**'
      - '.github/workflows/fg-6.0.yml'
      - '.github/workflows/gradle-forge-1.18.yml'

jobs:
  build:
    uses: ./.github/workflows/fg-6.0.yml
    with:
      version: 1.18
      java-version: 17